// TI calculator simulator
// Ken Shirriff, http://righto.com/ti
// Based on patent US3934233
// Code transcribed by Phil Mainwaring
//
// This file holds the source and object code to be executed.

var sourceCode = [
'.CLEAR   ZFA    ALL    ; Power on, clear flags',
'         ZFB    ALL   ',
'         AKA    ALL    ; Clear A and C',
'         AKC    ALL   ',
'         BET    RJ     ; Reset condition latch',
'.RJ      CAK    MANT1  ; Right justify A, maybe add minu...',
'         BILT   ZERO   ; Mantissa is zero?',
'.S       TFA    SIGN  ',
'         BIZ    RJ1    ; A is positive',
'         SAKAH  OV1    ; Minus sign is hex 14',
'         SAKAH  OV1   ',
'         BET    RJ1    ; Reset condition latch',
'.RJ1     CAK    LSD1   ; Right justify the display',
'         BIGE   DPTPOS',
'         CAK    EXP1  ',
'         BILT   DPTPOS',
'         SRLA   MANT   ; Shift A mantissa right',
'         SAKA   EXP1   ; Decrement A exponent',
'         BET    RJ1   ',
'.ZERO    AKA    ALL    ; A is zero, clear entire register',
'         ZFA    SIGN   ; Clear A sign flag',
'.DPTPOS  EXAB   ALL    ; Compute decimal point position...',
'         AKA    MANT1 ',
'         AAKA   MANT1 ',
'         EXAB   MANT   ; B mantissa is 2',
'         ABOA   EXP    ; Restore A exponent',
'.DP1     SAKA   EXP1   ; Shift B (2) left by A exponent...',
'         BILT   DP2   ',
'         SLLB   MANT  ',
'         BET    DP1   ',
'.DP2     ABOA   EXP   ',
'         TFB    F10   ',
'         BIO    ID1   ',
'.LOCK    SYNC          ; Debounce: wait for no key for a few cycles...',
'         SCAN         ',
'         BID    LOCK  ',
'         SYNC         ',
'         SCAN         ',
'         BID    LOCK  ',
'         ACKB   EXP   ',
'.IDLE    AKC    EXP    ; Idle loop entry',
'.ID1     ZFB    F10   ',
'.ID2     WAITNO ID3    ; Wait for key press or timeout',
'.ID4     SYNC         ',
'         SCAN         ',
'         BID    KEY    ; Key down',
'.FD1     ACKC   EXP1  ',
'         CCK    TIM4   ; Check number of timeouts',
'         BILT   FD3   ',
'         AKC    EXP   ',
'         SYNC         ',
'         WAITDK ID5    ; Turn off display, wait for DK',
'.FD3     TFB    F5     ; Test overflow',
'         BIZ    ID2   ',
'         SFB    F10   ',
'         AKC    MANT  ',
'         SCKC   MANT1 ',
'         BET    FD5    ; Reset condition latch',
'.FD5     ACKB   MANT  ',
'         ACKC   EXP1  ',
'         WAITNO FD4   ',
'.MINKEY  SFB    OP2    ; MINUS = flags II, III',
'         TFA    F3     ; If CD is clear...',
'         BIZ    PLSKEY ; perform subtract operation',
'         TFA    F4     ; Or EQ is clear...',
'         BIO    PLSKEY ; perform subtract operation',
'         TFA    OP1    ; Or not after multi/div...',
'         BIZ    PLSKEY ; perform subtract operation',
'         ZFB    OP2    ; Minus key as sign after mult or divide',
'         SFA    SIGN   ; Set sign to minus',
'         AKA    ALL    ; Clear A',
'         SFA    F9     ; Set ST flag (sign temp) for unary minus',
'         AAKA   DPT7   ; Set A exponent to 7',
'         ZFA    F3     ; Clear CD',
'         BET    S      ; Update display',
'.DIVKEY  SFB    OP2    ; DIV = flags II, III',
'.MLTKEY  SFB    OP1    ; MULT = flags I, III',
'.PLSKEY  SFB    OP3    ; PLUS = flag III',
'         TFA    F3     ; Clear display flag',
'         BIO    KS1   ',
'         TFA    F4     ; Equal flag',
'         BIZ    KS2   ',
'.KS1     ZFA    F4    ',
'         SFA    F5    ',
'         BET    KS2   ',
'.EQLKEY  SFA    F4     ; F4 (EQ) flag set for equals',
'.KS2     CAK    MANT1 ',
'         BILT   KS6    ; A mantissa == 0?',
'.KS3     CAK    OV1    ; Left justify A...',
'         BIGE   KS4    ; Digit has reached left?',
'         SLLA   MANT   ; Shift mantissa left',
'         AAKA   EXP1   ; Increment exponent',
'         BET    KS3   ',
'.DPTKEY  SFA    F10    ; Decimal point key...',
'         ZFA    F9     ; Set DPT flag, clear ST flag',
'         TFA    F3    ',
'         BIZ    DPTPOS',
'         ZFA    F3    ',
'         BET    ZERO  ',
'.CEKEY   TFA    F3    ',
'         BIO    DPTPOS',
'         SFA    F3    ',
'         ZFA    F10   ',
'         BET    ZERO  ',
'.KEY     ABOC   EXP    ; Process key down...',
'         TFB    F5     ; Test overflow',
'         BIO    LOCK   ; overflow never gets cleared???',
'         SYNC          ; Wait to debounce key',
'         SYNC         ',
'         SCAN         ',
'         BIU    IDLE  ',
'         AKB    ALL   ',
'         SYNC         ',
'         BKO    CLEAR  ; Clear key pressed?',
'         BKO    EQLKEY ; Equal key pressed?',
'         BKO    PLSKEY ; Plus key pressed?',
'         BKO    MINKEY ; Minus key pressed?',
'         BKO    MLTKEY ; Mult key pressed?',
'         BKO    DIVKEY ; Divide key pressed?',
'         BKO    CEKEY  ; CE key pressed?',
'         BKO    DPTKEY ; Decimal point key pressed?',
'         BKO    ZERKEY ; Zero key pressed?',
'         EXAB   ALL    ; Process digit key...',
'         AKCN   LSD1   ; Count key position into A',
'         EXAB   ALL   ',
'         BIC    DPTPOS ; No key pressed',
'.ZERKEY  TFA    F3     ; Clear display flag',
'         BIZ    NUM1  ',
'.CD      ZFA    SIGN  ',
'.CD1     AKA    ALL   ',
'         ZFA    F3    ',
'.NUM1    TFA    SIGN   ; Number: Digit is in B...',
'         BIZ    NUM3   ; Branch if A SIGN clear',
'         AAKAH  OV1    ; Test for 15 in OV1?',
'         AAKAH  OV1   ',
'         SAKAH  OV1   ',
'         SAKAH  OV1   ',
'         BIC    DPTPOS ; Borrow set if OV1 == 15?',
'.NUM2    TFA    F9     ; Test ST (sign temp) flag',
'         BIZ    NUM4  ',
'         TFA    F10   ',
'         BIO    NUM7  ',
'         EXAB   ALL   ',
'         CAK    MANT1 ',
'         EXAB   ALL   ',
'         BILT   DPTPOS',
'.NUM7    ZFA    F9     ; Clear ST flag',
'         BET    NUM6  ',
'.NUM3    CAK    MSD1  ',
'         BIGE   DPTPOS',
'         CAK    DPT7  ',
'         BIGE   DPTPOS',
'.NUM4    TFA    F10   ',
'         BIZ    NUM5  ',
'         AAKA   EXP1  ',
'.NUM5    SLLA   MANT  ',
'.NUM6    ABOA   LSD1  ',
'         BET    DPTPOS',
'.KS6     AKA    EXP   ',
'         ZFA    SIGN  ',
'         AAKA   DPT7  ',
'.KS7     ZFA    FD     ; Zeros temp(num) and dpt flag',
'         TFA    F5     ; Post flag',
'         BIO    POST  ',
'         TFA    OP3   ',
'         BIZ    POST  ',
'         ACKB   ALL   ',
'         TFB    F3     ; Constant flag',
'         BIZ    KS8   ',
'         ZFB    F3    ',
'         EXAB   ALL   ',
'         ABOC   ALL   ',
'         EXF    SIGN  ',
'.KS8     TFA    OP1   ',
'         BIO    MLTDIV',
'.ADDSUB  TFB    SIGN   ; Add / subtract...',
'         BIZ    AS1    ; Copy B sign to TEMP...',
'         SFA    F5    ',
'.AS1     TFA    OP2    ; Flip B sign for subtract...',
'         BIZ    AS2   ',
'         FFB    SIGN  ',
'.AS2     CAB    EXP    ; Make sure A exponent >= B exponent...',
'         BIGE   AS3   ',
'         EXAB   ALL    ; Exchange if A exponent smaller',
'         EXF    SIGN   ; And exchange the signs',
'.AS3     SAKA   EXP1   ; Shift A right until exponents equal...',
'         CAB    EXP    ; Infinite loop if B EXP == 0?',
'         BILT   AS4   ',
'         SRLA   MANT  ',
'         BET    AS3   ',
'.AS4     AAKA   EXP1   ; Exponents now equal',
'         BET    AS5    ; Reset condition',
'.AS5     CAB    MANT   ; Make sure A >= B...',
'         BIGE   AS6   ',
'         EXAB   ALL    ; If not, exchange exponents',
'         EXF    SIGN   ; and exchange signs',
'.AS6     CF     SIGN  ',
'         BIE    AS7    ; If signs equal, add...',
'         SABA   MANT   ; Otherwise subtract',
'         BET    AS8   ',
'.AS7     AABA   MANT   ; Add mantissas',
'.AS8     ZFB    SIGN   ; Restore B sign from TEMP flag...',
'         TFA    F5    ',
'         BIZ    POST  ',
'         SFB    SIGN  ',
'         ZFA    F5     ; And clear TEMP',
'         BET    POST   ; Done add/sub',
'.MLTDIV  CF     SIGN   ; Mult / div operation...',
'         ZFA    SIGN   ; Positive result if signs the same',
'         BIE    MD1   ',
'         SFA    SIGN   ; A, B signs different: negative result',
'.MD1     TFA    OP2   ',
'         BIC    DIV   ',
'         AAKC   ALL    ; Copy A to C',
'         AKA    MANT   ; Clear A mantissa',
'         AABA   EXP    ; Add A and B exponents',
'.M1      SCKC   LSD1   ; Repeat least-significant-digit of C times...',
'         BILT   M2    ',
'         AABA   MANT   ; Add B to A',
'         BET    M1    ',
'.M2      SRLC   MANT   ; Shift C right',
'         CCK    MANT1  ; Is C zero?',
'         BILT   MD2    ; Multiply done',
'         SRLA   MANT   ; Shift A right',
'         SAKA   EXP1   ; And decrease exponent',
'         BIGE   M1     ; Repeat the addition loop for the next C digit',
'         SFB    F5     ; Set overflow to indicate exponent negative',
'         BET    M1     ; But keep going',
'.DIV     CCK    MANT1  ; Divide code: A / B...',
'         BILT   ERR    ; Divide by zero',
'         AAKC   ALL    ; C / B, result goes in A...',
'.D1      AKA    MANT   ; Clear A mantissa',
'         CCK    MANT1 ',
'         BILT   MD2    ; Answer zero',
'         SABA   EXP   ',
'         BIGE   D2    ',
'         SFB    F5    ',
'.D2      CCB    MANT   ; Repeatedly subtract B from C...',
'         BILT   D3     ; Can\'t subtract any more',
'         SCBC   MANT   ; Subtract B from C',
'         AAKA   LSD1   ; And increment quotient in A',
'         BET    D2    ',
'.D3      CAK    MSD1   ; Value in A\'s most significant digit?',
'         BIGE   MD2    ; Divide done',
'         SLLC   MANT   ; Shift C left',
'         SLLA   MANT   ; Shift A left',
'         AAKA   EXP1   ; Increment exponent',
'         BINC   D2     ; If negative exponent becomes zero...',
'         ZFB    F5     ; Clear the overflow',
'         BET    D2     ; And keep going',
'.ERR     SFB    F5     ; Divide by zero - Set overflow',
'         BET    ZERO  ',
'.MD2     ABOC   ALL    ; Done: move B to C',
'.POST    AKB    EXP    ; Post-operation normalization...',
'         AKB    DPT7   ; Set B exponent to 7',
'         CAK    OV1    ; Is A overflow (top digit) set?',
'         BILT   P1     ; Branch if zero',
'         SRLA   MANT  ',
'         SAKA   EXP1  ',
'         BIGE   P1    ',
'         SFB    F5    ',
'.OVF     AABA   EXP   ',
'         AAKA   EXP1  ',
'         BIC    OVF1  ',
'.P1      TFB    F5     ; Test BF overflow',
'         BIO    OVF   ',
'         CAK    MANT1  ; Is A mantissa zero?',
'         BILT   P3     ; Branch if zero?',
'.P2      CAK    MSD1   ; Left-justify A...',
'         BIGE   P4    ',
'         SLLA   MANT  ',
'         AAKA   EXP1   ; Incrementing exponent each shift',
'         BET    P2    ',
'.ID5     BET    ID4    ; Random branch destination from WAITDK',
'.P3      ABOA   EXP    ; A is zero; set A exponent to 7',
'         ZFA    SIGN   ; And clear the sign',
'.P4      TFB    OP3    ; In middle of operation?',
'         BIZ    P7     ; Branch if operation completed',
'         SFB    F3     ; Set BF CONST',
'.P5      AAKC   ALL    ; Copy A to C',
'         CF     SIGN   ; Flip B SIGN if A and B SIGN different...',
'         BIE    P6    ',
'         FFB    SIGN  ',
'.P6      EXF    OPFGS  ; Move BF op flags to AF',
'         ZFB    OPFGS  ; and clear B op flags',
'.P7      SFA    F3     ; Set AF CD',
'         ZFA    F5     ; Clear AF POST/TEMP',
'         CAB    EXP    ; Shift A right until exponent <= 7...',
'         BILT   RJ     ; Branch if done',
'         SABA   EXP    ; Subtract 7 from A exponent',
'.P8      CAK    EXP1   ; Shift A right until exponent 0...',
'         BILT   P9     ; Add 7 back to exponent when done...',
'         SAKA   EXP1   ; otherwise ',
'         SRLA   MANT  ',
'         BET    P8     ; keep looping',
'.ID3     BET    ID4   ',
'.FD4     BET    DPTPOS ; Random WAITNO jump destination',
'.P9      AAKA   DPT7   ; Add 7 to A exponent',
'         BET    RJ     ; Branch',
'.KS4     TFA    SIGN   ; A negative?',
'         BIZ    KS9   ',
'         AKA    OV1    ; 1 -> OV1',
'         SAKA   OV1    ; 0 -> OV1 ?',
'         CAK    MANT1 ',
'         BILT   KS6   ',
'.KS5     CAK    MSD1  ',
'         BIGE   KS7   ',
'         SLLA   MANT  ',
'         AAKA   EXP1  ',
'         BET    KS5   ',
'.KS9     SRLA   MANT  ',
'         SAKA   EXP1  ',
'         BET    KS7   ',
'.OVF1    TFA    SIGN  ',
'         BIZ    DPTPOS',
'         SAKAH  OV1   ',
'         SAKAH  OV1   ',
'         BILT   DPTPOS ; Will this ever be true???',
];
var objectCode = [
1423, 1407, 1807, 1839, 5, 1755, 531, 1446,
12, 1992, 1992, 12, 1746, 21, 1757, 533,
1916, 1693, 12, 1807, 1414, 1855, 1803, 1563,
1852, 1598, 1693, 542, 1884, 26, 1598, 1432,
553, 1360, 1376, 545, 1360, 1376, 545, 1646,
1838, 1400, 1319, 1360, 1376, 616, 2013, 1777,
564, 1838, 1360, 1297, 1429, 42, 1336, 1836,
1723, 58, 1644, 2013, 1320, 1329, 1443, 77,
1444, 589, 1440, 77, 1393, 1350, 1807, 1351,
1552, 1411, 7, 1329, 1328, 1330, 1443, 594,
1444, 86, 1412, 1349, 86, 1348, 1755, 670,
1752, 299, 1868, 1565, 88, 1352, 1415, 1443,
21, 1411, 19, 1443, 533, 1347, 1416, 19,
1614, 1429, 545, 1360, 1360, 1376, 40, 1823,
1360, 1024, 1109, 1101, 1085, 1100, 1099, 1123,
1117, 1150, 1855, 1954, 1855, 533, 1443, 131,
1414, 1807, 1411, 1446, 148, 1976, 1976, 1992,
1992, 533, 1447, 152, 1448, 658, 1855, 1755,
1855, 533, 1415, 156, 1754, 21, 1744, 21,
1448, 155, 1565, 1868, 1586, 21, 1806, 1414,
1552, 1418, 1445, 765, 1442, 253, 1647, 1427,
173, 1395, 1855, 1615, 1526, 1440, 719, 1430,
178, 1349, 1441, 181, 1462, 1742, 185, 1855,
1526, 1693, 1742, 702, 1916, 185, 1565, 192,
1740, 196, 1855, 1526, 1494, 200, 1660, 201,
1548, 1398, 1445, 253, 1334, 1413, 253, 1494,
1414, 211, 1350, 1441, 740, 1583, 1804, 1550,
1714, 732, 1548, 216, 1948, 1787, 764, 1916,
1693, 216, 1333, 216, 1787, 762, 1583, 1804,
1787, 764, 1662, 237, 1333, 1772, 754, 1708,
1554, 237, 1754, 252, 1900, 1868, 1565, 237,
1397, 237, 1333, 19, 1615, 1822, 1808, 1752,
776, 1916, 1693, 264, 1333, 1550, 1565, 825,
1429, 773, 1755, 786, 1754, 276, 1868, 1565,
268, 43, 1598, 1414, 1426, 285, 1331, 1583,
1494, 283, 1462, 1529, 1401, 1347, 1413, 1742,
517, 1662, 1757, 809, 1693, 1916, 290, 43,
21, 1552, 5, 1446, 310, 1800, 1688, 1755,
670, 1754, 161, 1868, 1565, 305, 1916, 1693,
161, 1446, 21, 1992, 1992, 533, 
];
